[workspace]
members = [
    "libsm64_layout",
    "wafel_api",
    "wafel_app",
    "wafel_core",
    "wafel_data_path",
    "wafel_data_type",
    "wafel_graphics",
    "wafel_layout",
    "wafel_memory",
    "wafel_python",
    "wafel_timeline",
]
resolver = "2"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
