[workspace]
members = [
    "libsm64_layout",
    "wafel",
    "wafel_api",
    "wafel_core",
    "wafel_data_path",
    "wafel_data_type",
    "wafel_graphics",
    "wafel_layout",
    "wafel_memory",
    "wafel_python",
    "wafel_timeline",
]

[profile.release]
debug = true
incremental = true
