[package]
name = "wafel_data_path"
version = "0.1.0"
edition = "2018"

[dependencies]
wafel_data_type = { path = "../wafel_data_type" }
wafel_layout = { path = "../wafel_layout" }
wafel_memory = { path = "../wafel_memory" }
