name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - run: cargo build --release

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          pip install pipenv
          pipenv install --dev
      - run: pipenv run python build.py dist

      - uses: actions/upload-artifact@v2
        with:
          name: win_x64
          path: build/dist/*
