[package]
name = "wafel_layout"
version = "0.1.0"
edition = "2018"

[dependencies]
wafel_data_type = { path = "../wafel_data_type" }
object = "0.18.0"
gimli = "0.24.0"
serde = { version = "1.0.126", features = ["derive", "rc"] }
